#!/bin/sh
set -eu

CONSOLE_USER="$(/usr/bin/stat -f '%Su' /dev/console)"
if [ -n "$CONSOLE_USER" ] && [ "$CONSOLE_USER" != "root" ] && [ "$CONSOLE_USER" != "loginwindow" ]; then
    /usr/bin/sudo -u "$CONSOLE_USER" /usr/bin/defaults write com.adobe.CSXS.12 PlayerDebugMode -string 1
fi

exit 0
